server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/payflow
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6380

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    level: "%5p [cid=%X{cid}]"

resilience4j:
  circuitbreaker:
    instances:
      stripe:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true

      mockpsp:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true

payflow:
  webhook:
    stripe:
      # Local dev/test için dummy secret.
      # Gerçek ortamda environment variable üzerinden override edilmeli.
      secret: "dev-webhook-secret"